### ISSUE TITLE
Running error, seems to be missing files

### ISSUE THREAD

**Issue by jackyvava** [danielhalvorsen/Project_Turbulence_Modelling#2]
I have the same problem, when I run the 2D_Advection_parallell_turbulence.py file, it always warns that the files ‘datafiles/u/u_vel_t_0.npy’ are missing, but I have tried to run all the files. It doesn't generate this file, it seems like it's generated in advance?

**Comment by danielhalvorsen** [comment]
This is the same issue as in #1 and the answer is given there.

https://github.com/danielhalvorsen/Project_Turbulence_Modelling/issues/1#issuecomment-2143757803
